# Generated by Django 2.0.5 on 2018-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_hotsearchwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsearchwords',
            name='keywords',
            field=models.CharField(default='', max_length=20, verbose_name='热搜词'),
        ),
    ]
